
server:
  port: 8082
  servlet:
    context-path: /hsdemo

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboottest1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: localhost
    port: 6379
    password: 123456
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    max-idle: 200
    max-active: 2000
    max-wait: 1000
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hsexample.hsexample.entity

#showSql sql打印
logging:
  level:
    com.hsexample.hsexample.mapper: debug
